### ISSUE TITLE
libmarsxlog.so找不到异常

### ISSUE THREAD

**Issue by 1994jeff** [Tencent/mars#1045]
07-11 11:46:04.018  3298  3298 W System.err: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmarsxlog.so" not found
07-11 11:46:04.019  3298  3298 W System.err: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
07-11 11:46:04.019  3298  3298 W System.err: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
07-11 11:46:04.019  3298  3298 W System.err: 	at java.lang.System.loadLibrary(System.java:1664)
07-11 11:46:04.019  3298  3298 W System.err: 	at com.tencent.mars.xlog.Xlog.<clinit>(Xlog.java:21)

07-11 11:46:04.023  3298  3298 W System.err: java.lang.ExceptionInInitializerError: Xlog initializer so file error.
07-11 11:46:04.023  3298  3298 W System.err: 	at com.tencent.mars.xlog.Xlog.open(Xlog.java:32)

**Comment by monimonicaca** [comment]
一样的问题，请问解决了吗
