### ISSUE TITLE
python 解密工具可以支持python3吗？

### ISSUE THREAD

**Issue by DargonLee** [Tencent/mars#1090]
python decode_mars_crypt_log_file.py Vss_20221130.xlog
Traceback (most recent call last):
  File "decode_mars_crypt_log_file.py", line 9, in <module>
    import pyelliptic
  File "/Users/harlan/.pyenv/versions/2.7.18/lib/python2.7/site-packages/pyelliptic/__init__.py", line 43, in <module>
    from .openssl import OpenSSL
  File "/Users/harlan/.pyenv/versions/2.7.18/lib/python2.7/site-packages/pyelliptic/openssl.py", line 527, in <module>
    raise Exception("Couldn't load OpenSSL lib ...")
Exception: Couldn't load OpenSSL lib ...

**Comment by zhanlan123** [comment]
使用java版本的试试。
核心，命令行版本：
https://github.com/wustMeiming/XlogDecoder
UI版本：
https://github.com/zhanlan123/YXlogDecode
