### ISSUE TITLE
xlog解密失败，libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

### ISSUE THREAD

**Issue by lgh001** [Tencent/mars#1117]
环境：
macOS: 13.0.1 (22A400)
openssl: 3.3.6
pyelliptic: 1.5.10
python:2.7

解密log的时候报错

错误信息：
Traceback (most recent call last):
  File "/Users/environment/tools/log/decode_mars_crypt_log_file.py", line 9, in <module>
    import pyelliptic
  File "build/bdist.macosx-10.9-x86_64/egg/pyelliptic/__init__.py", line 43, in <module>
  File "build/bdist.macosx-10.9-x86_64/egg/pyelliptic/openssl.py", line 640, in <module>
  File "build/bdist.macosx-10.9-x86_64/egg/pyelliptic/openssl.py", line 129, in __init__
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/opt/homebrew/Cellar/openssl@3/3.1.0/lib/libcrypto.3.dylib, 0x0006): tried: '/opt/homebrew/Cellar/openssl@3/3.1.0/lib/libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openssl@3/3.1.0/lib/libcrypto.3.dylib' (no such file), '/opt/homebrew/Cellar/openssl@3/3.1.0/lib/libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

求解

**Comment by zhanlan123** [comment]
https://github.com/zhanlan123/YXlogDecode
https://github.com/wustMeiming/XlogDecoder
用着两个java版本试试。

**Comment by zhanlan123** [comment]
https://github.com/zhanlan123/YXlogDecode

**Comment by zhanlan123** [comment]
> 环境： macOS: 13.0.1 (22A400) openssl: 3.3.6 pyelliptic: 1.5.10 python:2.7
> 
> 解密log的时候报错
> 
> 错误信息： Traceback (most recent call last): File "/Users/environment/tools/log/decode_mars_crypt_log_file.py", line 9, in import pyelliptic File "build/bdist.macosx-10.9-x86_64/egg/pyelliptic/**init**.py", line 43, in File "build/bdist.macosx-10.9-x86_64/egg/pyelliptic/openssl.py", line 640, in File "build/bdist.macosx-10.9-x86_64/egg/pyelliptic/openssl.py", line 129, in **init** File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/**init**.py", line 366, in **init** self._handle = _dlopen(self._name, mode) OSError: dlopen(/opt/homebrew/Cellar/openssl@3/3.1.0/lib/libcrypto.3.dylib, 0x0006): tried: '/opt/homebrew/Cellar/openssl@3/3.1.0/lib/libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openssl@3/3.1.0/lib/libcrypto.3.dylib' (no such file), '/opt/homebrew/Cellar/openssl@3/3.1.0/lib/libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
> 
> 求解
https://github.com/zhanlan123/YXlogDecode  最新版本已经支持zstd和zip格式。

**Comment by izouxv** [comment]
一个基于docker的xlog解码器
https://github.com/izouxv/xlog
