### ISSUE TITLE
AttributeError: dlsym(0x30833d9e0, ECDH_OpenSSL): symbol not found

### ISSUE THREAD

**Issue by jagtu** [Tencent/mars#1158]
当我执行命令的时候，报了这个错：
```python
Traceback (most recent call last):
  File "/Users/abc/Documents/xlog_dec_tool/crypt/decode_mars_crypt_log_file.py", line 9, in <module>
    import pyelliptic
  File "build/bdist.macosx-13.4-x86_64/egg/pyelliptic/__init__.py", line 43, in <module>
  File "build/bdist.macosx-13.4-x86_64/egg/pyelliptic/openssl.py", line 528, in <module>
  File "build/bdist.macosx-13.4-x86_64/egg/pyelliptic/openssl.py", line 180, in __init__
  File "/Users/abc/.pyenv/versions/2.7.18/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/Users/abc/.pyenv/versions/2.7.18/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x30833d9e0, ECDH_OpenSSL): symbol not found
```

pip 23.2.1 from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip (python 3.11)
Python 2.7.18
OpenSSL 3.1.2 1 Aug 2023 (Library: OpenSSL 3.1.2 1 Aug 2023)

**Comment by zhanlan123** [comment]
应该式OpenSSL版本太高了。可以用：https://github.com/zhanlan123/YXlogDecode 这个基于java和c的解密

**Comment by gogi2010** [comment]
> 应该是OpenSSL版本太高了。可以用：https://github.com/zhanlan123/YXlogDecode 这个基于java和c的解密

这个工程我试过，拖拽文件进去只会提示，"Please drag a xlog file or xlog directory here"
我的是mac 版本：13.5.2, M1芯片，仅供参考。

最后通过这个方案解决了：https://github.com/Tencent/mars/issues/969
