### ISSUE TITLE
日志解密失败，部分日志丢失

### ISSUE THREAD

**Issue by 1zhangshasha1** [Tencent/mars#1171]
执行python脚本解密，报错：
Traceback (most recent call last):
  File "decode_mars_nocrypt_log_file.py", line 124, in DecodeBuffer
    tmpbuffer = decompressor.decompress(str(tmpbuffer))
error: Error -3 while decompressing: invalid stored block lengths
Traceback (most recent call last):
  File "decode_mars_nocrypt_log_file.py", line 121, in DecodeBuffer
    tmpbuffer = next(decompressor.read_from(ZstdDecompressReader(str(tmpbuffer)), 100000, 1000000))
ZstdError: zstd decompress error: Unknown frame descriptor
Traceback (most recent call last):
  File "decode_mars_nocrypt_log_file.py", line 124, in DecodeBuffer
    tmpbuffer = decompressor.decompress(str(tmpbuffer))
error: Error -3 while decompressing: invalid stored block lengths
Traceback (most recent call last):
  File "decode_mars_nocrypt_log_file.py", line 124, in DecodeBuffer
    tmpbuffer = decompressor.decompress(str(tmpbuffer))
error: Error -3 while decompressing: invalid stored block lengths
导致解析出来的日志文件，8点到10点两个小时的日志丢失，有什么解决办法嘛

**Comment by 445146313** [comment]
看看别的回答不是有老哥给了java版现成的解压软件吗

**Comment by zhanlan123** [comment]
试试这个：桌面和Android都有
https://github.com/zhanlan123/YXlogDecode
