### ISSUE TITLE
xlog日志没有做加密，只是用了压缩，现在解压日志大部分都是乱码，用java解密工具报错，有大佬帮忙看下是什么原因吗？

### ISSUE THREAD

**Issue by TeddyQT** [Tencent/mars#1190]
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot read the array length because "<parameter1>" is null
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.get(Unknown Source)
	at top.yinlingfeng.xlog.decode.ui.DecodeFrame$DecodeLogTask.done(DecodeFrame.java:1030)
	at java.desktop/javax.swing.SwingWorker$5.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at java.desktop/sun.swing.AccumulativeRunnable.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by TeddyQT** [comment]
用py进行解压，报错：[F]decode_log_file.py decompress err, Error -3 while decompressing: invalid stored block lengths
[F]decode_log_file.py decode error len=49779, result:_buffer[1983]:0 != MAGIC_NUM_START 
[F]decode_log_file.py log seq:3-1 is missing
[F]decode_log_file.py decompress err, Error -3 while decompressing: invalid distance too far back
[F]decode_log_file.py decode error len=1948, result:_buffer[78206]:0 != MAGIC_NUM_START 
[F]decode_log_file.py log seq:3-18141 is missing

**Comment by zhanlan123** [comment]
发下日志文件

**Comment by TeddyQT** [comment]
[logs_20231201.xlog.zip](https://github.com/Tencent/mars/files/13608547/logs_20231201.xlog.zip)
@zhanlan123 帮忙看下谢谢

**Comment by zhanlan123** [comment]
[logs_20231201.xlog.log](https://github.com/Tencent/mars/files/13609298/logs_20231201.xlog.log)
解压出来，感觉是不是你后面用了加密，前面有没有用加密。需要看看你代码怎么写的了

**Comment by zhanlan123** [comment]
这是java版本更新后的解密的。
