### ISSUE TITLE
Non-interactively mars native build failure under the Mac env.

### ISSUE THREAD

**Issue by easyfan** [Tencent/mars#156]
Under the Mac env, with the python version 2.7.10, the non-interactively mars native build will fail.
For example, run:

`python build_android.py 1 armeabi-v7a`

Finally it will fail, with following error traces:

> Traceback (most recent call last):
  File "build_android.py", line 300, in <module>
    main()
  File "build_android.py", line 222, in main
    return build_android_mars_shared_libs()
  File "build_android.py", line 169, in build_android_mars_shared_libs
    if 0 != build_android_mars_static_libs(_path, _arch):
  File "build_android.py", line 124, in build_android_mars_static_libs
    if 0 != os.system(NDK_BUILD_CMD %(_arch) + "../" + BUILD_MARS_PATHS[i]):
TypeError: not all arguments converted during string formatting

Such issue will also happens on non-interactively xlog native build, whatever static or share libs.

**Comment by easyfan** [comment]
Now have a fix on this issue. Will pull request recently.
