### ISSUE TITLE
UnknownHostException  `android.oa.com` in Sample/server

### ISSUE THREAD

**Issue by 3c** [Tencent/mars#3]
```
Enter menu:
1. start server on Mac, Linux or Cygwin.
2. start server on Windows.
3. exit.
1
Downloading http://android.oa.com/gradle/gradle-2.14.1-bin.zip

Exception in thread "main" java.net.UnknownHostException: android.oa.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
cx:Server cx$ ping android.oa.com
ping: cannot resolve android.oa.com: Unknown host
cx:Server cx$ cat start_server.py
#!/usr/bin/env python

```

**Comment by 3c** [comment]
in `mars/samples/Server/gradle/wrapper`

change 
`distributionUrl=http://android.oa.com/gradle/gradle-2.14.1-bin.zip`
to
`distributionUrl=https://services.gradle.org/distributions/gradle-2.14.1-all.zip`

it's ok 

```
cx:Server cx$ python start_server.py
Enter menu:
1. start server on Mac, Linux or Cygwin.
2. start server on Windows.
3. exit.
1
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Download https://jcenter.bintray.com/com/google/protobuf/protobuf-gradle-plugin/0.7.3/protobuf-gradle-plugin-0.7.3.pom
Download https://jcenter.bintray.com/com/google/guava/guava/10.0.1/guava-10.0.1.pom
Download https://jcenter.bintray.com/com/google/guava/guava-parent/10.0.1/guava-parent-10.0.1.pom
```

**Comment by shockcao** [comment]
这里遗漏了修改  android.oa.com是我们的内网服务   我提交一下修改  谢谢

**Comment by bberljw** [comment]
Downloading https://services.gradle.org/distributions/gradle-2.14.1-all.zip
Exception in thread "main" javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake


可否手动下载下来，覆盖到某个文件夹？网太卡，一直出错。

**Comment by rokistar** [comment]
@bberljw 可以，我使用了Charles做Map Local
