### ISSUE TITLE
本地编译成功后，运行时抛出java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by rorschach** [Tencent/mars#303]
之前项目的逻辑使用gradle依赖Mars的方式走通了所有逻辑，但本地编译流程出现问题．
下载master分支的代码后，按照`Mars Android 接入指南`使用**ndk-r11c**本地编译Mars，编译成功．
但是将生成的.java文件和.so拷贝到项目中后，发现所有.java文件中的native方法都提示`cannot resolve JNI fuction`，且项目运行时直接崩溃．

崩溃堆栈:
[stack_trace.txt](https://github.com/Tencent/mars/files/1320675/stack_trace.txt)

使用Mars的代码段:
![new_client](https://user-images.githubusercontent.com/10024661/30690243-1725feaa-9ef6-11e7-8914-81fa0cb51bb1.png)
![client](https://user-images.githubusercontent.com/10024661/30690245-1977aeb0-9ef6-11e7-95e8-aae09a7cc846.png)

编译流程:
![build_0](https://user-images.githubusercontent.com/10024661/30688898-f7499320-9ef1-11e7-9168-450bab969299.png)
![build_1](https://user-images.githubusercontent.com/10024661/30688919-0427d93a-9ef2-11e7-8e18-ad905960c5fc.png)

项目结构:
![package](https://user-images.githubusercontent.com/10024661/30688957-1ea702cc-9ef2-11e7-8b68-9512fcfb9aff.png)

提示 `cannot resolve JNI fuction` 的文件:
![stnlogic_warn](https://user-images.githubusercontent.com/10024661/30688976-2c8fa68c-9ef2-11e7-8bc3-df9138eaf723.png)
![xlog_warn](https://user-images.githubusercontent.com/10024661/30689629-1f66d352-9ef4-11e7-9684-13d72f814a5e.png)

build.gradle:
![gradle](https://user-images.githubusercontent.com/10024661/30688992-3842da30-9ef2-11e7-8ae8-aea0fb371130.png)

**Comment by rorschach** [comment]
若将生成的.so文件放置在 /libs 下面而不是 /src/main/jniLibs 下面的话，则抛出以下异常

```
E/art: No implementation found for void com.tencent.mars.stn.StnLogic.setLonglinkSvrAddr(java.lang.String, int[], java.lang.String) (tried Java_com_tencent_mars_stn_StnLogic_setLonglinkSvrAddr and Java_com_tencent_mars_stn_StnLogic_setLonglinkSvrAddr__Ljava_lang_String_2_3ILjava_lang_String_2)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: rorschach.me.messagedemo, PID: 30913
                  java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mars.stn.StnLogic.setLonglinkSvrAddr(java.lang.String, int[], java.lang.String) (tried Java_com_tencent_mars_stn_StnLogic_setLonglinkSvrAddr and Java_com_tencent_mars_stn_StnLogic_setLonglinkSvrAddr__Ljava_lang_String_2_3ILjava_lang_String_2)
                      at com.tencent.mars.stn.StnLogic.setLonglinkSvrAddr(Native Method)
                      at com.tencent.mars.stn.StnLogic.a(SourceFile:286)
                      at com.erplus.message.longlink.LongLinkClient.init(SourceFile:63)
                      at com.erplus.message.longlink.LongLinkClient.<init>(SourceFile:46)
                      at rorschach.me.messagedemo.App.onCreate(App.java:31)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5638)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1625)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6374)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by garryyan** [comment]
查看下手机上 /data/data/packag/lib 目录有相应的so吗

**Comment by rorschach** [comment]
之前的两种情况下都没有对应的.so文件，按照[issue164](https://github.com/Tencent/mars/issues/164)重新配置gradle文件后可以看到.so文件了，但是抛出一下异常:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: rorschach.me.messagedemo, PID: 15025
                  java.lang.UnsatisfiedLinkError: classPath:com/tencent/mars/comm/PlatformComm$C2Java
                      at com.tencent.mars.BaseEvent.onCreate(Native Method)
                      at com.tencent.mars.a.a(SourceFile:47)
                      at com.erplus.message.longlink.LongLinkClient.init(SourceFile:66)
                      at com.erplus.message.longlink.LongLinkClient.<init>(SourceFile:46)
                      at rorschach.me.messagedemo.App.onCreate(App.java:31)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4583)
                      at android.app.ActivityThread.access$1500(ActivityThread.java:154)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5290)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

```
 /data/data/package/lib:
![so_path](https://user-images.githubusercontent.com/10024661/30726631-a9912a20-9f7e-11e7-9bde-897fe0b5d7b8.png)

gradle:
![gradle](https://user-images.githubusercontent.com/10024661/30726573-4d412194-9f7e-11e7-8be6-962be086590e.png)
![gradle_1](https://user-images.githubusercontent.com/10024661/30726576-4e5263d6-9f7e-11e7-9b25-836056369809.png)

**Comment by garryyan** [comment]
看你代码里 com/tencent/mars/comm/PlatformComm$C2Java 是否有这个class

**Comment by rorschach** [comment]
直接用的Mars源码编译，源码里是有的
![c2java](https://user-images.githubusercontent.com/10024661/30726813-ae7cb31e-9f7f-11e7-9b2f-31fb76c1a19a.png)
![c2java_1](https://user-images.githubusercontent.com/10024661/30726841-efac1262-9f7f-11e7-9cc5-0e813b043f19.png)

**Comment by garryyan** [comment]
编的debug版本还是release版本，是不是把代码混淆了？

**Comment by liuyongyi0110** [comment]
你好，我也遇到这个问题了，我已经把com.tencent.mars的包下的文件都没有混淆，但是还是这个问题
