### ISSUE TITLE
xlog混淆问题,急求解决方案

### ISSUE THREAD

**Issue by AndyAls** [Tencent/mars#319]
不开混淆 测试正常,开了混淆,报错,解决不了,不知道什么原因 =急急急 `下面是错误日志`
` FATAL EXCEPTION: main
                                                   Process: com.geely.mars.xlogdemo, PID: 21692
                                                   java.lang.IllegalStateException: Could not execute method for android:onClick
                                                       at android.support.v7.app.m$a.onClick(Unknown Source)
                                                       at android.view.View.performClick(View.java:5702)
                                                       at android.widget.TextView.performClick(TextView.java:10896)
                                                       at android.view.View$PerformClick.run(View.java:22546)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:158)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at android.support.v7.app.m$a.onClick(Unknown Source) 
                                                       at android.view.View.performClick(View.java:5702) 
                                                       at android.widget.TextView.performClick(TextView.java:10896) 
                                                       at android.view.View$PerformClick.run(View.java:22546) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:158) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7225) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                       at com.geely.mars.xlogdemo.a.a.b(Unknown Source)
                                                       at com.geely.mars.xlogdemo.a.a.a(Unknown Source)
                                                       at com.geely.mars.xlogdemo.a.a.a(Unknown Source)
                                                       at com.geely.mars.xlogdemo.MainActivity.onClick(Unknown Source)
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at android.support.v7.app.m$a.onClick(Unknown Source) 
                                                       at android.view.View.performClick(View.java:5702) 
                                                       at android.widget.TextView.performClick(TextView.java:10896) 
                                                       at android.view.View$PerformClick.run(View.java:22546) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:158) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7225) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) `

**Comment by AndyAls** [comment]
这个问题已经解决,不是库的问题
