### ISSUE TITLE
error: Error -3 while decompressing: invalid distance code

### ISSUE THREAD

**Issue by ChanJLee** [Tencent/mars#323]
解密日志的时候报错
堆栈：

```
Traceback (most recent call last):
  File "/Users/chan/Documents/xlog-server/decode_mars_crypt_log_file.py", line 142, in DecodeBuffer
    tmpbuffer = decompressor.decompress(str(tmpbuffer))
error: Error -3 while decompressing: invalid distance too far back
Traceback (most recent call last):
  File "/Users/chan/Documents/xlog-server/decode_mars_crypt_log_file.py", line 142, in DecodeBuffer
    tmpbuffer = decompressor.decompress(str(tmpbuffer))
error: Error -3 while decompressing: invalid distance too far back
```

**Comment by garryyan** [comment]
解密后的文件打开看下，搜索：```[F]decode_log_file.py decompress```   看有几处？ 是否必现？

**Comment by ChanJLee** [comment]
必现。 

我跟demo中唯一的区别就是不曾调用close，而是每次在退到后台时flush，是否跟这个有关？

```
~~~~~ begin of mmap ~~~~~
^^^^^^^^^^Sep 26 2017^^^14:19:21^^^^^^^^^^[7265,7265][2017-11-06 +0800 08:36:34]
del time out files time: 1
get mmap time: 10
MARS_URL: 
MARS_PATH: master
MARS_REVISION: f4f0dab
MARS_BUILD_TIME: 2017-09-26 14:19:00
MARS_BUILD_JOB: mars_xlog_sdk/mars_libs
log appender mode:0, use mmap:1
~~~~~ end of mmap ~~~~~[7377,7377][2017-11-06 +0800 08:36:37]
[F]decode_log_file.py decode error len=7436, result:log length:7363, buffer[8025]:7 != MAGIC_END 
[I][2017-11-06 +8.0 08:51:59.193][7265, 1*][CollinsDefinitionView][, , 0][fold text
[I][2017-11-06 +8.0 08:51:59.194][7265, 1*][CollinsDefinitionView][, , 0][open arrow
[I][2017-11-06 +8.0 08:51:59.261][7265, 1*][CollinsDefinitionView][, , 0][foldText height = 114
[I][2017-11-06 +8.0 08:51:59.261][7265, 1*][CollinsDefinitionView][, , 0][foldText lp.height = 114
[I][2017-11-06 +8.0 08:52:03.227][7265, 1*][CollinsDefinitionView][, , 0][close arrow
[I][2017-11-06 +8.0 08:52:03.230][7265, 1*][CollinsDefinitionView][, , 0][animationExpandAndCollapse
[I][2017-11-06 +8.0 08:52:03.230][7265, 1*][CollinsDefinitionView][, , 0][animationExpandAndCollapse onAnimationStart:223
[I][2017-11-06 +8.0 09:06:31.882][7265, 1*][CollinsDefinitionView][, , 0][foldText lp.height = 171
~~~~~ begin of mmap ~~~~~
[F]decode_log_file.py log seq:3-3 is missing
[I][2017-11-06 +8.0 10:13:55.669][7265, 1*][CollinsDefinitionView][, , 0][fold text
[I][2017-11-06 +8.0 10:13:55.670][7265, 1*][CollinsDefinitionView][, , 0][open arrow
[I][2017-11-06 +8.0 10:13:55.728][7265, 1*][CollinsDefinitionView][, , 0][foldText height = 171
[I][2017-11-06 +8.0 10:13:55.728][7265, 1*][CollinsDefinitionView][, , 0][foldText lp.height = 171
[I][2017-11-06 +8.0 10:13:59.578][7265, 1*][CollinsDefinitionView][, , 0][fold text
[I][2017-11-06 +8.0 10:13:59.578][7265, 1*][CollinsDefinitionView][, , 0][open arrow
~~~~~ end of mmap ~~~~~[24710,24710][2017-11-06 +0800 12:49:32]
~~~~~ begin of mmap ~~~~~
^^^^^^^^^^Sep 26 2017^^^14:19:21^^^^^^^^^^[24710,24710][2017-11-06 +0800 12:49:32]
del time out files time: 2
get mmap time: 11
MARS_URL: 
MARS_PATH: master
MARS_REVISION: f4f0dab
MARS_BUILD_TIME: 2017-09-26 14:19:00
MARS_BUILD_JOB: mars_xlog_sdk/mars_libs
log appender mode:0, use mmap:1
~~~~~ end of mmap ~~~~~[24817,24817][2017-11-06 +0800 12:49:34]
~~~~~ begin of mmap ~~~~~
[F]decode_log_file.py decompress err, Error -3 while decompressing: invalid distance too far back
~~~~~ end of mmap ~~~~~[30494,30494][2017-11-06 +0800 14:21:14]
~~~~~ begin of mmap ~~~~~
^^^^^^^^^^Sep 26 2017^^^14:19:21^^^^^^^^^^[30494,30494][2017-11-06 +0800 14:21:14]
del time out files time: 1
get mmap time: 8
MARS_URL: 
MARS_PATH: master
MARS_REVISION: f4f0dab
MARS_BUILD_TIME: 2017-09-26 14:19:00
MARS_BUILD_JOB: mars_xlog_sdk/mars_libs
log appender mode:0, use mmap:1
~~~~~ end of mmap ~~~~~[30597,30597][2017-11-06 +0800 14:21:16]
[F]decode_log_file.py decompress err, Error -3 while decompressing: invalid distance too far back
[I][2017-11-06 +8.0 14:44:48.105][30494, 1*][CollinsDefinitionView][, , 0][fold text
[I][2017-11-06 +8.0 14:44:48.106][30494, 1*][CollinsDefinitionView][, , 0][open arrow
[I][2017-11-06 +8.0 14:44:48.182][30494, 1*][CollinsDefinitionView][, , 0][foldText height = 114
[I][2017-11-06 +8.0 14:44:48.182][30494, 1*][CollinsDefinitionView][, , 0][foldText lp.height = 114
~~~~~ begin of mmap ~~~~~
^^^^^^^^^^Sep 26 2017^^^14:19:21^^^^^^^^^^[11881,11881][2017-11-06 +0800 15:36:46]
del time out files time: 0
get mmap time: 7
MARS_URL: 
MARS_PATH: master
MARS_REVISION: f4f0dab
MARS_BUILD_TIME: 2017-09-26 14:19:00
MARS_BUILD_JOB: mars_xlog_sdk/mars_libs
log appender mode:0, use mmap:1
~~~~~ end of mmap ~~~~~[11985,11985][2017-11-06 +0800 15:36:48]
^^^^^^^^^^Sep 26 2017^^^14:19:21^^^^^^^^^^[11985,11985][2017-11-06 +0800 15:36:48]
del time out files time: 0
get mmap time: 7
MARS_URL: 
MARS_PATH: master
MARS_REVISION: f4f0dab
MARS_BUILD_TIME: 2017-09-26 14:19:00
MARS_BUILD_JOB: mars_xlog_sdk/mars_libs
log appender mode:0, use mmap:1
```

**Comment by garryyan** [comment]
你的app是多进程应用吗

**Comment by ChanJLee** [comment]
有部分多进程的代码，这是因为多进程导致的问题吗？

**Comment by ChanJLee** [comment]
部分代码是，但是经过确认，多进程代码里并没有引用xlog的类

**Comment by garryyan** [comment]
打开控制台日志，重定向控制台日志到文件中(记得带上进程信息，时间信息)，出现问题的时候把控制台日志和解密后的xlog日志文件发到我邮箱：1173828173@qq.com

**Comment by StartWithWzk** [comment]
这个的解决办法是什么呢？我也遇到一样的问题了

**Comment by NamedJack** [comment]
请问一下这个问题 怎么解决的呢

**Comment by ChanJLee** [comment]
解决方法就是，针对每个进程，单独用一个xlog输出文件，比如 process_name.xlog
