### ISSUE TITLE
mars_android_sdk 监听网络变化时发生空指针异常（非必现）

### ISSUE THREAD

**Issue by yuhui2016github** [Tencent/mars#354]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.tencent.mars.BaseEvent$ConnectionReceiver.isNetworkChange(BaseEvent.java:86)
	at com.tencent.mars.BaseEvent$ConnectionReceiver.checkConnInfo(BaseEvent.java:72)
	at com.tencent.mars.BaseEvent$ConnectionReceiver.onReceive(BaseEvent.java:51)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1218)
	... 7 more

**Comment by garryyan** [comment]
应该[在这一行](https://github.com/Tencent/mars/blob/master/mars/libraries/mars_android_sdk/src/main/java/com/tencent/mars/BaseEvent.java#L86) 空指针，欢迎pr。
