### ISSUE TITLE
python gen_key.py报错，提示：WindowsError: [Error 193] %1 不是有效的 Win32

### ISSUE THREAD

**Issue by pinguo-hexiaogang** [Tencent/mars#377]
完成的错误日志：
PS C:\source\mars-1.2.1\mars\log\crypt> python gen_key.py
Traceback (most recent call last):
  File "gen_key.py", line 3, in <module>
    import pyelliptic
  File "build\bdist.win-amd64\egg\pyelliptic\__init__.py", line 43, in <module>
  File "build\bdist.win-amd64\egg\pyelliptic\openssl.py", line 528, in <module>
  File "build\bdist.win-amd64\egg\pyelliptic\openssl.py", line 67, in __init__
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 不是有效的 Win32

**Comment by pinguo-hexiaogang** [comment]
环境：
windows10 64
Python 2.7.12 64
Win64OpenSSL-1_0_2n

**Comment by garryyan** [comment]
你本地的环境有问题。如果已经确认了没有64位， 32位混合使用的话。

我印象中见另外一个同学遇到过类似的问题，是因为System32 或者SysWoW64目录下的某个openssl的文件不对，把相应的copy覆盖就行了。具体细节不记得了

**Comment by pinguo-hexiaogang** [comment]
1.我都是使用的64位的版本

2.你说的是这个issue吗？https://github.com/Tencent/mars/issues/286
这个和我的问题不一样啊。我System32下有libeay32.dll文件了，copy到SysWoW64下面也不能解决啊。

**Comment by garryyan** [comment]
很可能是windows10的问题

**Comment by pinguo-hexiaogang** [comment]
我的系统是win10家庭版

**Comment by m5314** [comment]
这个问题是怎么解决的呢？我系统win7也遇到了，同样我用的都是64位的版本

**Comment by m5314** [comment]
已解决！
方法如下
1.找到这行代码File "C:\Python27\lib\ctypes_init_.py", line 362, in init
2.在这行代码前添加打印语句prinf self._name
3.保存，重新执行python gen_key.py
4.然后看输出，我看到的是C:\Program Files (x86)\Intel\iCLS Client\libeay32.dll
5.由此得到系统没有获取我添加到系统盘的libeay32.dll库，所以将自己的libeay32.dll替换即可

**Comment by wangyingjie55** [comment]
> 完成的错误日志：
> PS C:\source\mars-1.2.1\mars\log\crypt> python gen_key.py
> Traceback (most recent call last):
> File "gen_key.py", line 3, in 
> import pyelliptic
> File "build\bdist.win-amd64\egg\pyelliptic__init__.py", line 43, in 
> File "build\bdist.win-amd64\egg\pyelliptic\openssl.py", line 528, in 
> File "build\bdist.win-amd64\egg\pyelliptic\openssl.py", line 67, in **init**
> File "C:\Python27\lib\ctypes__init__.py", line 362, in **init**
> self._handle = _dlopen(self._name, mode)
> WindowsError: [Error 193] %1 不是有效的 Win32

请问这个问题解决了吗？ 我也同样遇到了这个问题  我也是win10

**Comment by 13272438611** [comment]
我也遇到了相同的问题，跟#286比较相似。
一开始是Exception: Couldn't load OpenSSL lib ...
然后下载了libeay32.dll分别把32位和64位的版本拷贝到System32 和SysWoW64目录下，
于是出现了WindowsError: [Error 193] %1 不是有效的 Win32的提示，
折腾了很久，最后把SysWoW64下的libeay32.dll也用32为的覆盖就可以了。

**Comment by mrchengwenlong** [comment]
> > 完成的错误日志：
> > PS C:\source\mars-1.2.1\mars\log\crypt> python gen_key.py
> > Traceback (most recent call last):
> > File "gen_key.py", line 3, in
> > import pyelliptic
> > File "build\bdist.win-amd64\egg\pyelliptic__init__.py", line 43, in
> > File "build\bdist.win-amd64\egg\pyelliptic\openssl.py", line 528, in
> > File "build\bdist.win-amd64\egg\pyelliptic\openssl.py", line 67, in **init**
> > File "C:\Python27\lib\ctypes__init__.py", line 362, in **init**
> > self._handle = _dlopen(self._name, mode)
> > WindowsError: [Error 193] %1 不是有效的 Win32
> 
> 请问这个问题解决了吗？ 我也同样遇到了这个问题 我也是win10

问题解决了嘛 我也是win10
