### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mars.BaseEvent.onCreate()

### ISSUE THREAD

**Issue by songzhangzhang** [Tencent/mars#447]
最近集成了tinker并发布了一个tinker补丁包之后，出现了很多mars的UnsatisfiedLinkError异常。

异常栈：
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mars.BaseEvent.onCreate() (tried Java_com_tencent_mars_BaseEvent_onCreate and Java_com_tencent_mars_BaseEvent_onCreate__)
	at com.tencent.mars.BaseEvent.onCreate(Native Method)
	at com.tencent.mars.Mars.onCreate(Mars.java:44)
	at com.wuage.imcore.net.NetworkChannelMarsImpl.<init>(NetworkChannelMarsImpl.java:58)
	at com.wuage.imcore.protocol.Session.<init>(Session.java:84)
	at com.wuage.imcore.IMAccount.<init>(IMAccount.java:83)
	at com.wuage.imcore.IMAccount.getInstance(IMAccount.java:68)
	at com.wuage.steel.im.ImApplication.initImListener(ImApplication.java:158)
	at com.wuage.steel.im.ImApplication.initIMCore(ImApplication.java:143)
	at com.wuage.steel.im.ImApplication.initData(ImApplication.java:131)
	at com.wuage.steel.im.ImApplication.onCreate(ImApplication.java:100)
	at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:180)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1056)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3099)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

崩溃机型分布如下：
<img width="1190" alt="20180828110400" src="https://user-images.githubusercontent.com/23444382/44698330-18191e00-aab2-11e8-8bd2-a31e327ee66d.png">

**Comment by garryyan** [comment]
本地能重现吗？ 这种只能慢慢分析，看是不是so损坏了
