### ISSUE TITLE
主线程初始化Xlog 部分手机卡死

### ISSUE THREAD

**Issue by DEHUITANG** [Tencent/mars#465]
接入xlog的时候红米4X启动初始化会出现卡死,lib 打印的日志:
09-22 11:44:23.728 24840-24846/*** IIart: Thread[3,tid=24846,WaitingInMainSignalCatcherLoop,Thread*=0x7f8f441e00,peer=0x12cefd30,"Signal Catcher"]: reacting to signal 3
09-22 11:44:28.840 24840-24840/*** W/libbacktrace: bool ThreadEntry::Wait(int): pthread_cond_timedwait for value 2 failed: Connection timed out
09-22 11:44:28.840 24840-24840/*** E/libbacktrace: void SignalHandler(int, siginfo_t *, void *): Timed out waiting for unwind thread to indicate it completed.
09-22 11:44:33.903 24840-24846/*** W/libbacktrace: bool ThreadEntry::Wait(int): pthread_cond_timedwait for value 3 failed: Connection timed out
    bool BacktraceCurrent::UnwindThread(size_t): Timed out waiting for signal handler to indicate it finished.
09-22 11:44:34.180 24840-24846/*** I/art: Wrote stack traces to '/data/anr/traces.txt'
我们使用进程号作为文件名称排除了多进程写同一文件导致的问题
有人遇到过类似的问题么？要怎么解决这个问题？（现在没有找到很好的解决方案，只能在子线程中初始化，但是会出现这个问题的手机就没有日志了）

**Comment by garryyan** [comment]
给文件读写权限了吗？给的日志路径对吗？
还有anr文件中的栈贴下

**Comment by DEHUITANG** [comment]
文件权限确定是打开的，路径也是没有问题的，其它手机都是能正常使用的

"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x7650bd88 self=0x7f8f440a00
  | sysTid=7458 nice=-10 cgrp=default sched=0/0 handle=0x7f9341baa0
  | state=R schedstat=( 21595796528 15285216 264 ) utm=2142 stm=17 core=1 HZ=100
  | stack=0x7fdda79000-0x7fdda7b000 stackSize=8MB
  | held mutexes=
  kernel: __switch_to+0x70/0x7c
  kernel: 0xffffffc0769dc5c0
  native: #00 pc 0000000000027dd8  /data/app/com.**.**-1/lib/arm64/libmarsxlog.so (???)
  native: #01 pc cec7107ead6a4c7a  ???
  at com.tencent.mars.xlog.Xlog.appenderOpen(Native method)
  at com.**.**.log.XlogManager.initXlog(XlogManager.java:60)
  at com.**.**.log.XlogManager.init(XlogManager.java:45)
  at com.**.**.manager.IMInitManager.init(IMInitManager.java:200)
  at com.**.**.AndroidApplication._initIMKit(AndroidApplication.java:167)
  at com.**.**.AndroidApplication.onCreate(AndroidApplication.java:101)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5515)
  at android.app.ActivityThread.-wrap2(ActivityThread.java:-1)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1594)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:163)
  at android.app.ActivityThread.main(ActivityThread.java:6239)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

这个是anr的堆栈日志

**Comment by garryyan** [comment]
native: #00 pc 0000000000027dd8 /data/app/com..-1/lib/arm64/libmarsxlog.so (???)   
根据你的符号信息还原出来行号，看卡在了哪一行

**Comment by kamaelyoung** [comment]
如果你配置的 日志文件要卸载sdcard 需要先有sd 的读写权限。。。。否则就会卡死
