### ISSUE TITLE
centos 7 会报  File "/home/admin/.local/lib/python2.7/site-packages/pyelliptic/ecc.py", line 89, in __init__     self.privkey, self.pubkey_x, self.pubkey_y = self._generate()   File "/home/admin/.local/lib/python2.7/site-packages/pyelliptic/ecc.py", line 223, in _generate     raise Exception("[OpenSSL] EC_KEY_generate_key FAIL ... " + OpenSSL.get_error()) Exception: [OpenSSL] EC_KEY_generate_key FAIL ... error:100B3043:elliptic curve routines:EC_KEY_generate_key:passed a null parameter

### ISSUE THREAD

**Issue by xiaoxuetu** [Tencent/mars#490]
如图： 
 File "/home/admin/.local/lib/python2.7/site-packages/pyelliptic/ecc.py", line 89, in __init__
    self.privkey, self.pubkey_x, self.pubkey_y = self._generate()
  File "/home/admin/.local/lib/python2.7/site-packages/pyelliptic/ecc.py", line 223, in _generate
    raise Exception("[OpenSSL] EC_KEY_generate_key FAIL ... " + OpenSSL.get_error())
Exception: [OpenSSL] EC_KEY_generate_key FAIL ... error:100B3043:elliptic curve routines:EC_KEY_generate_key:passed a null parameter

**Comment by lin-xin** [comment]
@xiaoxuetu 最后找到解决方法了没呢？

**Comment by xiaoxuetu** [comment]
@lin-xin 没有哦，最后还是用回Ubuntu了就没有这个问题了

**Comment by ouyangpeng** [comment]
![image](https://user-images.githubusercontent.com/5885735/55726316-1947fb80-5a42-11e9-9fe5-3f68706dc5fd.png)

```shell
Exception: [OpenSSL] EC_KEY_generate_key FAIL ... error:100B3043:elliptic curve routines:EC_KEY_generate_key:passed a null parameter
Traceback (most recent call last):
  File "log_decode_encrypted_log_file.py", line 133, in DecodeBuffer
    svr = pyelliptic.ECC(curve='secp256k1')
  File "build/bdist.linux-x86_64/egg/pyelliptic/ecc.py", line 89, in __init__
    self.privkey, self.pubkey_x, self.pubkey_y = self._generate()
  File "build/bdist.linux-x86_64/egg/pyelliptic/ecc.py", line 223, in _generate
    raise Exception("[OpenSSL] EC_KEY_generate_key FAIL ... " + OpenSSL.get_error())
Exception: [OpenSSL] EC_KEY_generate_key FAIL ... error:100B3043:elliptic curve routines:EC_KEY_generate_key:passed a null parameter
Traceback (most recent call last):
  File "log_decode_encrypted_log_file.py", line 133, in DecodeBuffer
    svr = pyelliptic.ECC(curve='secp256k1')
  File "build/bdist.linux-x86_64/egg/pyelliptic/ecc.py", line 89, in __init__
    self.privkey, self.pubkey_x, self.pubkey_y = self._generate()
  File "build/bdist.linux-x86_64/egg/pyelliptic/ecc.py", line 223, in _generate
    raise Exception("[OpenSSL] EC_KEY_generate_key FAIL ... " + OpenSSL.get_error())
Exception: [OpenSSL] EC_KEY_generate_key FAIL ... error:100B3043:elliptic curve routines:EC_KEY_generate_key:passed a null parameter
Traceback (most recent call last):
  File "log_decode_encrypted_log_file.py", line 133, in DecodeBuffer
    svr = pyelliptic.ECC(curve='secp256k1')
  File "build/bdist.linux-x86_64/egg/pyelliptic/ecc.py", line 89, in __init__
    self.privkey, self.pubkey_x, self.pubkey_y = self._generate()
  File "build/bdist.linux-x86_64/egg/pyelliptic/ecc.py", line 223, in _generate
    raise Exception("[OpenSSL] EC_KEY_generate_key FAIL ... " + OpenSSL.get_error())
Exception: [OpenSSL] EC_KEY_generate_key FAIL ... error:100B3043:elliptic curve routines:EC_KEY_generate_key:passed a null parameter
Traceback (most recent call last):
  File "log_decode_encrypted_log_file.py", line 133, in DecodeBuffer
    svr = pyelliptic.ECC(curve='secp256k1')
  File "build/bdist.linux-x86_64/egg/pyelliptic/ecc.py", line 89, in __init__
    self.privkey, self.pubkey_x, self.pubkey_y = self._generate()
  File "build/bdist.linux-x86_64/egg/pyelliptic/ecc.py", line 223, in _generate
    raise Exception("[OpenSSL] EC_KEY_generate_key FAIL ... " + OpenSSL.get_error())
Exception: [OpenSSL] EC_KEY_generate_key FAIL ... error:100B3043:elliptic curve routines:EC_KEY_generate_key:passed a null parameter
```

openssl 的 版本为 1.1.1

![image](https://user-images.githubusercontent.com/5885735/55726362-34b30680-5a42-11e9-9afe-a1b2b6e1a6e9.png)


看 https://github.com/Tencent/mars/wiki/Xlog-%E5%8A%A0%E5%AF%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%BC%95 

说
![image](https://user-images.githubusercontent.com/5885735/55726379-409ec880-5a42-11e9-9584-b72d48cf0d78.png)

还是不行的

**Comment by garryyan** [comment]
环境问题，只能靠你自己来解决了 @ouyangpeng

**Comment by boycs007** [comment]
centos遇到同样问题，yum install openssl就ok了
