### ISSUE TITLE
iOS python build_ios.py 报错

### ISSUE THREAD

**Issue by meiwuzhao** [Tencent/mars#523]
你好! 按照文档运行了下python build_ios.py 能帮看下报错问题在哪么,谢谢! 

PPDdeiMac:~ merlin_wu$ cd /Users/merlin_wu/mars/mars 
PPDdeiMac:mars merlin_wu$ python build_ios.py 
Enter menu:
1. Clean && build mars.
2. Clean && build xlog.
3. Gen iOS mars Project.
4. Exit
1
[[==BUILD_DESCRIPTION==]]Revision: 3bcc6e0 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<style type="text/css">.description table {    margin: 10px 0 15px 0;    border-collapse: collapse;    font-family: Helvetica, "Hiragino Sans GB", Arial, sans-serif;    font-size: 11px;    line-height: 16px;    color: #737373;    background-color: white;    margin: 10px 12px 10px 12px;}.description td,th { border: 1px solid #ddd; padding: 3px 10px; }.description th { padding: 5px 10px; }.description a { color: #0069d6; }.description a:hover { color: #0050a3; text-decoration: none; }.description h5 { font-size: 14px; }</style><div class="description"><h5>PublicComponent</h5><table><thead><tr><th align="left">KEY</th><th align="left">VALUE</th></tr></thead><tr><td align="left">Branch</td><td align="left">master</td></tr><tr><td align="left">BuildTag</td><td align="left"></td></tr><tr><td align="left">BuildTime</td><td align="left">2019-01-23 17:33:23</td></tr><tr><td align="left">Revision</td><td align="left">3bcc6e0</td></tr></table></div>
sh: cmake: command not found
!!!!!!!!!!!build os fail!!!!!!!!!!!!!!!
PPDdeiMac:mars merlin_wu$

**Comment by wakacoon** [comment]
需要安装cmake工具

**Comment by LKShadow** [comment]
你好，我按照文档使用Python3 运行build_ios.py报错。已经通过brew安装了cmake工具。信息如下：
```
Traceback (most recent call last):
  File "build_ios.py", line 166, in <module>
    main()
  File "build_ios.py", line 149, in main
    num = raw_input('Enter menu:\n1. Clean && build mars.\n2. Clean && build xlog.\n3. Gen iOS mars Project.\n4. Exit\n')
NameError: name 'raw_input' is not defined
```
可以看下是什么原因吗
