### ISSUE TITLE
单个日志文字过长时候，解密会失败，提示字符超长

### ISSUE THREAD

**Issue by renyuanlong** [Tencent/mars#542]

**Comment by garryyan** [comment]
解密是不限制字符长度的，请贴上脚本报错的错误信息

**Comment by renyuanlong** [comment]
461503532
                            
                            
                                
                                    邮箱：461503532@qq.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


            在2019年03月01日 17:50，garryyan 写道： 解密是不限制字符长度的，请贴上脚本报错的错误信息



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Tencent/mars","title":"Tencent/mars","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Tencent/mars"}},"updates":{"snippets":[{"icon":"PERSON","message":"@garryyan in #542: 解密是不限制字符长度的，请贴上脚本报错的错误信息"}],"action":{"name":"View Issue","url":"https://github.com/Tencent/mars/issues/542#issuecomment-468607829"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Tencent/mars/issues/542#issuecomment-468607829",

"url": "https://github.com/Tencent/mars/issues/542#issuecomment-468607829",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by renyuanlong** [comment]
Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffertmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid stored block lengths Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid stored block lengths Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 139, in DecodeBuffer tea_key = svr.get_ecdh_key(client.get_pubkey())File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 271, in get_ecdh_keyreturn self.raw_get_ecdh_key(pubkey_x, pubkey_y)File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 324, inraw_get_ecdh_key OpenSSL.EC_KEY_free(own_key)UnboundLocalError: local variable 'own_key' referenced before assignment Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid block type Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 152, in DecodeBuffer tmpbuffer = decompressor.decompress(str(decompress_data))error: Error -3 while decompressing: invalid stored block lengths Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 139, in DecodeBuffer tea_key = svr.get_ecdh_key(client.get_pubkey())File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 271, in get_ecdh_keyreturn self.raw_get_ecdh_key(pubkey_x, pubkey_y)File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 324, inraw_get_ecdh_key OpenSSL.EC_KEY_free(own_key)UnboundLocalError: local variable 'own_key' referenced before assignment Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 152, in DecodeBuffer tmpbuffer = decompressor.decompress(str(decompress_data))error: Error -3 while decompressing: invalid code lengths set Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 139, in DecodeBuffer tea_key = svr.get_ecdh_key(client.get_pubkey()) File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 271, in get_ecdh_keyreturn self.raw_get_ecdh_key(pubkey_x, pubkey_y)File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 324, inraw_get_ecdh_key OpenSSL.EC_KEY_free(own_key)UnboundLocalError: local variable 'own_key' referenced before assignment Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 139, in DecodeBuffer tea_key = svr.get_ecdh_key(client.get_pubkey())File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 271, in get_ecdh_keyreturn self.raw_get_ecdh_key(pubkey_x, pubkey_y)File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 324, inraw_get_ecdh_key OpenSSL.EC_KEY_free(own_key)UnboundLocalError: local variable 'own_key' referenced before assignment Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 139, in DecodeBuffer tea_key = svr.get_ecdh_key(client.get_pubkey())File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 271, in get_ecdh_keyreturn self.raw_get_ecdh_key(pubkey_x, pubkey_y)File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 324, inraw_get_ecdh_key OpenSSL.EC_KEY_free(own_key)UnboundLocalError: local variable 'own_key' referenced before assignment Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 152, in DecodeBuffer tmpbuffer = decompressor.decompress(str(decompress_data))error: Error -3 while decompressing: invalid code lengths set Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid code lengths set Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid stored block lengths Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid block type Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 139, in DecodeBuffertea_key = svr.get_ecdh_key(client.get_pubkey())File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 271, inget_ecdh_keyreturn self.raw_get_ecdh_key(pubkey_x, pubkey_y)File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 324, in raw_get_ecdh_keyOpenSSL.EC_KEY_free(own_key)UnboundLocalError: local variable 'own_key' referenced before assignment Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid distance too far back Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 152, in DecodeBuffer tmpbuffer = decompressor.decompress(str(decompress_data))error: Error -3 while decompressing: invalid stored block lengths Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid distance too far back Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 152, in DecodeBuffer tmpbuffer = decompressor.decompress(str(decompress_data))error: Error -3 while decompressing: invalid stored block lengths Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 152, in DecodeBuffer tmpbuffer = decompressor.decompress(str(decompress_data))error: Error -3 while decompressing: invalid code lengths set Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid block type Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid code lengths set Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid stored block lengths Traceback (most recent call last): File "decode_mars_crypt_log_file.py", line 139, in DecodeBuffer tea_key = svr.get_ecdh_key(client.get_pubkey())File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 271, in get_ecdh_keyreturn self.raw_get_ecdh_key(pubkey_x, pubkey_y)File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 324, inraw_get_ecdh_key OpenSSL.EC_KEY_free(own_key)UnboundLocalError: local variable 'own_key' referenced before assignment Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid stored block lengths Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid block type Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid stored block lengths Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid distance too far back Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 152, in DecodeBuffer tmpbuffer = decompressor.decompress(str(decompress_data))error: Error -3 while decompressing: invalid code lengths set Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid stored block lengths Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid distance too far back Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 139, in DecodeBuffer tea_key = svr.get_ecdh_key(client.get_pubkey())File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 271, in get_ecdh_keyreturn self.raw_get_ecdh_key(pubkey_x, pubkey_y) File "build/bdist.macosx-10.6-intel/egg/pyelliptic/ecc.py", line 324, in raw_get_ecdh_keyOpenSSL.EC_KEY_free(own_key)UnboundLocalError: local variable 'own_key' referenced before assignment Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid distance too far back Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 152, in DecodeBuffer tmpbuffer = decompressor.decompress(str(decompress_data))error: Error -3 while decompressing: invalid distance too far back Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 144, in DecodeBuffer tmpbuffer = decompressor.decompress(str(tmpbuffer))error: Error -3 while decompressing: invalid distance too far back Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 152, in DecodeBuffer tmpbuffer = decompressor.decompress(str(decompress_data))error: Error -3 while decompressing: invalid stored block lengths Traceback (most recent call last):File "decode_mars_crypt_log_file.py", line 152, in DecodeBuffer tmpbuffer = decompressor.decompress(str(decompress_data))error: Error -3 while decompressing: invalid code lengths set



    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            461503532
                            
                            
                                
                                    邮箱：461503532@qq.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


            在2019年03月01日 18:56，任远龙 写道： 
        
            



    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            461503532
                            
                            
                                
                                    邮箱：461503532@qq.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


            在2019年03月01日 17:50，garryyan 写道： 解密是不限制字符长度的，请贴上脚本报错的错误信息



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Tencent/mars","title":"Tencent/mars","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Tencent/mars"}},"updates":{"snippets":[{"icon":"PERSON","message":"@garryyan in #542: 解密是不限制字符长度的，请贴上脚本报错的错误信息"}],"action":{"name":"View Issue","url":"https://github.com/Tencent/mars/issues/542#issuecomment-468607829"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Tencent/mars/issues/542#issuecomment-468607829",

"url": "https://github.com/Tencent/mars/issues/542#issuecomment-468607829",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by garryyan** [comment]
这应该是日志文件损坏导致的。
原因一般常见于多进程写一份日志文件，存储损坏
