### ISSUE TITLE
System.loadLibrary("marsxlog")报错java.lang.UnsatisfiedLinkError: classPath:com/tencent/mars/xlog/Xlog

### ISSUE THREAD

**Issue by qioLiu** [Tencent/mars#560]
2019-03-19 11:44:04.666 17328-17328/com.example.testxlog E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.testxlog, PID: 17328
    java.lang.UnsatisfiedLinkError: classPath:com/tencent/mars/xlog/Xlog
        at java.lang.Runtime.nativeLoad(Native Method)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1014)
        at java.lang.System.loadLibrary(System.java:1672)
        at com.example.testxlog.impl.XlogImpl.init(XlogImpl.java:21)
        at com.example.testxlog.proxy.LogManager.initLog(LogManager.java:62)
        at com.example.testxlog.MainActivity.onCreate(MainActivity.java:18)
        at android.app.Activity.performCreate(Activity.java:7436)
        at android.app.Activity.performCreate(Activity.java:7426)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by liuyongyi0110** [comment]
我也遇到了，请问你有解决吗？

**Comment by Jack-Xiao** [comment]
我也遇到了同样的问题，写下解决方法：不要修改包名和类名
https://github.com/Tencent/mars/issues/620
