### ISSUE TITLE
由于项目需求，需要编译一个armeabi-v7a架构的so，但是就是加载不了，报错如下

### ISSUE THREAD

**Issue by liuyongyi0110** [Tencent/mars#609]
2019-05-09 22:08:18.384 12809-12809/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: wallet.qapple.hk.dev, PID: 12809
    java.lang.UnsatisfiedLinkError: classPath:com/tencent/mars/xlog/Xlog
        at java.lang.Runtime.nativeLoad(Native Method)
        at java.lang.Runtime.doLoad(Runtime.java:1099)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1014)
        at java.lang.System.loadLibrary(System.java:1661)
        at hk.qapple.mars.initIm.ImStartUtils.onCreate(ImStartUtils.java:56)
        at wallet.qapple.hk.view.viewcompl.activity.MainActivity.initUI(MainActivity.java:88)
        at wallet.qapple.hk.base.BaseNoTitleActivity.onCreate(BaseNoTitleActivity.java:92)
        at android.app.Activity.performCreate(Activity.java:7110)
        at android.app.Activity.performCreate(Activity.java:7101)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2922)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3047)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1777)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:6861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

有没有大佬遇到过。

**Comment by liangxiwei** [comment]
编译选项要改一下codecc.sh里面要改为armeabi-v7a架构的，我比较疑惑的是我编译出来的xlog大小是90多k，直接引用他们的是50多k，为啥会差那么多

**Comment by garryyan** [comment]
你上层有 com/tencent/mars/xlog/Xlog.java 这个类吗？

**Comment by liuyongyi0110** [comment]
已经解决了
