### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by xiayibo** [Tencent/mars#777]
linker: "/data/app/com.tencent.mars.sample-V0cVxJl2-j87HPiVRwEtMg==/lib/x86/libmarsstn.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)

Process: com.tencent.mars.sample, PID: 4673
    java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mars.stn.StnLogic.setDebugIP(java.lang.String, java.lang.String) (tried Java_com_tencent_mars_stn_StnLogic_setDebugIP and Java_com_tencent_mars_stn_StnLogic_setDebugIP__Ljava_lang_String_2Ljava_lang_String_2)
        at com.tencent.mars.stn.StnLogic.setDebugIP(Native Method)
        at com.tencent.mars.sample.SampleApplicaton.onCreate(SampleApplicaton.java:74)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Android Studio 自带模拟器  api 29  Android 10.0

**Comment by sshsu** [comment]
I also come across the problem, can some people help?
