### ISSUE TITLE
java.lang.IllegalStateException: Pid 19445 has exceeded the number of permissible registered listeners. Ignoring request to add

### ISSUE THREAD

**Issue by YvesCheung** [Tencent/mars#829]
java.lang.IllegalStateException: Pid 19445 has exceeded the number of permissible registered listeners. Ignoring request to add.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2384)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenForSubscriber(ITelephonyRegistry.java:1140)
	at android.telephony.TelephonyRegistryManager.listenForSubscriber(TelephonyRegistryManager.java:231)
	at android.telephony.TelephonyManager.listen(TelephonyManager.java:5617)

[NetStatusUtil.java](https://github.com/Tencent/mars/blob/master/mars/libraries/mars_android_sdk/src/main/java/com/tencent/mars/comm/NetStatusUtil.java)
```
public static int getStrength(final Context context) 
```
这个方法每调用一次就多注册一个listener是不是有点问题

**Comment by yeyelow** [comment]
+1

**Comment by mwshubham** [comment]
+1

**Comment by bsrikanth88** [comment]
+1

**Comment by bsrikanth88** [comment]
+1

**Comment by daohieu91** [comment]
+1

**Comment by EmotionDemo** [comment]
how can i remove this listener?

**Comment by whsgzcy** [comment]
+1

**Comment by FreddyChen** [comment]
telManager.listen(mMobilePhoneStateListener, PhoneStateListener.LISTEN_NONE)

**Comment by 2193531059** [comment]
Where should this line of code that removes the listener be called, and will it affect the original message push?

**Comment by 2193531059** [comment]
> telManager.listen(mMobilePhoneStateListener, PhoneStateListener.LISTEN_NONE)



> telManager.listen(mMobilePhoneStateListener, PhoneStateListener.LISTEN_NONE)

Where should this line of code that removes the listener be called, and will it affect the original message push?
